default: &default
  adapter: postgresql
  encoding: utf8
  host: localhost
  username: postgres
  password: postgres
  pool: 5

development:
  <<: *default
  database: users_contract_development

test:
  <<: *default
  database: users_contract_test

production:
  <<: *default
  database: users_contract_production
  username: users_contract
  password: <%= ENV['USERS_CONTRACT_DATABASE_PASSWORD'] %>
